### PR TITLE
RU: translation correction

### PR DESCRIPTION
**Pull request by Sinitsaa**

### CODE REVIEW

**Review by alama — COMMENTED** [review]
The coverage script failed, you may have some extra lines somewhere

**Review by alama — APPROVED** [review]
Coverage working again

**Comment by alama** [comment]
@Sinitsaa SIGH, you had a merge conflict BUT all you did was removed the merge conflict markers, so NOW you have dup IDs

**Comment by Sinitsaa** [comment]
Fuck...

**Comment by alama** [comment]
```
./translated files/UI/ui_mainmode.csv:3769 Treasure_Platform#3
./translated files/UI/ui_mainmode.csv:3770 CommunicationHistory#0
./translated files/UI/ui_mainmode.csv:3771 GoodJob#0
./translated files/UI/ui_mainmode.csv:3772 GoodJobWithoutComment#0
./translated files/UI/ui_mainmode.csv:3773 Party#0
./translated files/UI/ui_mainmode.csv:3774 MultiParty#0
./translated files/UI/ui_mainmode.csv:3775 Employ#0
```

have fun with dup lines....

**Comment by alama** [comment]
ok, you want NOT fail the EN check, you have only change the lines for your language, let me FUCKING fix it for you....

**Comment by Sinitsaa** [comment]
Do not get mad. I'll fix it now.

**Comment by alama** [comment]
Oh, I am ALWAYS mad, and already fixed it for you

**Comment by Sinitsaa** [comment]
merge, please

**Comment by alama** [comment]
Need to FUCKING review......
LATER!

**Pull request merged**
