### PR TITLE
PT: Adding Arks Handbook Translated 

### PR DESCRIPTION
**Pull request by BadHowst**
Adding Arks Handbook Translated to test Font and Accents
Adicionando Arks Handbook

### CODE REVIEW

**Comment by BadHowst** [comment]
Waiting for approval so i can send more and test out the patch for Font and Accents

**Comment by BadHowst** [comment]
Read-me and some files added, after Merging i am gonna create a Debug patch to check the files in-game

**Comment by alama** [comment]
you can add a file to the folder named "release.sed" that replaces "á" with "a"
the FR teams use it look so: https://github.com/Arks-Layer/PSO2ENPatchCSV/blob/FR/release.sed

**Comment by BadHowst** [comment]
> you can add a file to the folder named "release.sed" that replaces "á" with "a"
> the FR teams use it look so: https://github.com/Arks-Layer/PSO2ENPatchCSV/blob/FR/release.sed

I decided to use words that wont require accents, this way even the players are not gonna have much problems ingame

**Comment by BadHowst** [comment]
These files are all set, i will be sending more later today

**Pull request closed without merging**
