### PR TITLE
EN: small things

### PR DESCRIPTION
**Pull request by YukaLily**
I'm not sure whether it was okay to lengthen that alma line but this sounds much better

### CODE REVIEW

**Comment by alama** [comment]
You need to MOVE changed out of the FILES folder

https://github.com/Arks-Layer/PSO2ENPatchCSV#user-content-notice

**Comment by YukaLily** [comment]
Ah, I'm so sorry.
Moved the file out!

**Comment by YukaLily** [comment]
did I go too far

**Comment by alama** [comment]
You just have some spelling "mistakes"

```musn't
alloweth
Prayeth
./Story/Episode 3/ra_033970.csv:ra_033970_0030#0,"""'tis only a leak of its power, but, nothing short of extraordinary. Prayeth thou be cautious."""
./Story/Episode 3/ra_033970.csv:ra_033970_0050#0,"""'t musn't be alloweth to break through the final \""Gate\"". May that happen, all will be lost."""
```


I going to assume this is in Old English?

**Comment by YukaLily** [comment]
Yeah, it was my best effort, at least.

**Comment by Kyle873** [comment]
Yeah, that's how she speaks. Her very specific wording will be annoying for aspell to deal with.

**Comment by alama** [comment]
just add the words to `_aspell/PSO2.en_Chat.dict` list

**Comment by alama** [comment]
@YukaLily if this merge request is good, edit "WIP: " out of the title

**Comment by YukaLily** [comment]
Alrights!

**Comment by YukaLily** [comment]
I am done with this for awhile, I'll just open another request when I submit new translations?

**Pull request merged**
