### PR TITLE
EN: EP3 Blue Node

### PR DESCRIPTION
**Pull request by ScienceJumps**
Translated this section. It was annoying. Please let me know if the meaning is conveyed properly.

### CODE REVIEW

**Comment by alama** [comment]
Look, you have the move the files OUT of the Files folder, just type `../../Story/Episode 3` so you move the files into the correct place

**Comment by alama** [comment]
Since you had disable outsider from pushing into your patch-1 branch, I can not fix up the issues with your PR

**Comment by Aida-Enna** [comment]
Is this still being worked on? @ScienceJumps

**Comment by ScienceJumps** [comment]
I apologise, I'm a bit swamped with work, but I will get back to it when I
can :(

**Pull request merged**
