### PR TITLE
Es: prueba

### PR DESCRIPTION
**Pull request by NozomiRem**

### CODE REVIEW

**Comment by alama** [comment]
SIGH, you did not merge `ES-v50500_rc_78` in this PR, let fix THAT first

**Comment by NozomiRem** [comment]
delete pr delete folder download new edit and nothing

**Comment by alama** [comment]
`git fetch upsteam`
`git merge ES-v50500_rc_78`
`git mergetool`
RESOLVED isses

**Comment by NozomiRem** [comment]
.......

**Comment by alama** [comment]
DUDE, I was going to PUSH the fix into your PR....

**Comment by NozomiRem** [comment]
this is already being repeated too much in my pr

**Comment by NozomiRem** [comment]
I try to update it and do not want to update,
erase and I download it again and it keeps giving me errors

**Pull request closed without merging**
