### PR TITLE
Es: misc

### PR DESCRIPTION
**Pull request by Reixaldo**

### CODE REVIEW

**Comment by alama** [comment]
ui_craft_name.csv is normally done by PSO2es repos, can you revert the changes?

**Comment by Reixaldo** [comment]
ok

**Comment by alama** [comment]
???

**Comment by alama** [comment]
@Reixaldo never mind, I was thinking of the wrong file

**Comment by Reixaldo** [comment]
¡Geh!

**Comment by Reixaldo** [comment]
I have to do many things ... I lost some ... recover others ... well ... as I go to mourn a corner in a fetal position

**Pull request merged**
