### PR TITLE
EN: Item UI stuff

### PR DESCRIPTION
**Pull request by DabirSA**
Various parts of item lab translated, made consistent with other parts, reworded and corrected. Various potentials translated, reworded, made consistent with other uses of certain terms (ie affixes-> special abilities) and clipping fixed.

### CODE REVIEW

**Comment by acffordyce973** [comment]
Are all these bracket changes intentional or just a side-effect from whatever editor you're using?

**Comment by DabirSA** [comment]
They're intentional. Is there an problem with them?

**Comment by acffordyce973** [comment]
Kinda. The lines have been changed but not actually translated.

**Comment by DabirSA** [comment]
What problems does that cause?

**Pull request closed without merging**
