### PR TITLE
ES: EN string in line 205#0 and 134#1 translated (NOPE)

### PR DESCRIPTION
**Pull request by mega-leon**

### CODE REVIEW

**Review by Aida-Enna — COMMENTED** [review]
Aside from the translation (which seems fine to me but my Spanish is really rusty), looking good! Just gotta wait for Blazter to give it the OK :thumbsup:

**Comment by alama** [comment]
Since you had disabled outsider from update your branch, your PR  is out of date

**Comment by Aida-Enna** [comment]
What do you mean? You can't update their branch for them because they've disabled PRs on their fork?

**Comment by TheBlazter** [comment]
Since this PR have translation errors, what i can not solve, because his branch have disabled PR's, and the file is outdated, i will close it.

**Pull request closed without merging**
